const I18N={
ar:{branches:'الفروع الخمسة',cart:'السلة',heroKicker:'جديد • فيليه السمك',heroTitle:'قرمشة تسمعها.<br>وطعم ترجع له.',heroBody:'فيليه سمك مقرمش مع بطاطا، خبز، كريم توم، كولسلو ومخلل. وجبة كاملة جاهزة من أقرب فرع.',orderNow:'اطلب الآن',fastFlow:'طلب سريع • اسم ورقم فقط',completeMeal:'وجبة كاملة',aed:'درهم',flow1:'اختار وجبتك',flow2:'أضف ما يناسبها',flow3:'اختار الفرع',flow4:'أرسل أو ادفع',menuTitle:'شو نفسك اليوم؟',menuNote:'منيو أفندي بصور موحّدة، أسعار واضحة وطلب سريع من أقرب فرع.',branchTitle:'اختار الفرع الأقرب',branchNote:'كل طلب يروح مباشرة إلى واتساب الفرع المحدد.',yourCart:'سلة الطلب',completeIt:'كمّل وجبتك',smartSuggestions:'اقتراحات ذكية',total:'المجموع',continueCheckout:'اختيار الفرع وإكمال الطلب',checkout:'إكمال الطلب',selectBranch:'اختار الفرع الأقرب',name:'الاسم',phone:'رقم الهاتف',fulfilment:'طريقة الاستلام',delivery:'توصيل',takeaway:'استلام',dinein:'داخل المطعم',payment:'طريقة الدفع',whatsappCod:'WhatsApp / الدفع عند الاستلام',availableNow:'متاح الآن',gatewayPending:'بانتظار بيانات بوابة البنك',orderValue:'قيمة الطلب',sendWhatsapp:'إرسال الطلب إلى WhatsApp الفرع',privacy:'يُرسل الطلب فقط إلى الفرع الذي اخترته.',all:'الكل',meals:'الوجبات',bowls:'الباولز',wraps:'الراب',extras:'إضافات',drinks:'مشروبات',add:'إضافة',empty:'السلة فارغة. اختار وجبتك أولاً.',added:'تمت الإضافة إلى السلة',chooseFirst:'أضف منتجاً واحداً على الأقل',chooseBranch:'اختار الفرع',openMap:'فتح الموقع ↗',newOrder:'طلب جديد - Affandi Chicken Dubai',customer:'العميل',branch:'الفرع',receipt:'طريقة الاستلام',payMethod:'طريقة الدفع',orderTotal:'المجموع'},
en:{branches:'Five branches',cart:'Cart',heroKicker:'NEW • FISH FILLET',heroTitle:'Hear the crunch.<br>Come back for the taste.',heroBody:'Crispy fish fillet with fries, bread, garlic cream, coleslaw and pickles. A complete meal from your nearest branch.',orderNow:'Order now',fastFlow:'Fast order • name and phone only',completeMeal:'Complete meal',aed:'AED',flow1:'Choose your meal',flow2:'Make it yours',flow3:'Select a branch',flow4:'Send or pay',menuTitle:'What are you craving?',menuNote:'Affandi menu with consistent imagery, clear prices and fast ordering from your nearest branch.',branchTitle:'Choose your nearest branch',branchNote:'Your order goes directly to the WhatsApp of the selected branch.',yourCart:'Your order',completeIt:'Complete your meal',smartSuggestions:'Smart add-ons',total:'Total',continueCheckout:'Select branch & checkout',checkout:'Checkout',selectBranch:'Choose your nearest branch',name:'Name',phone:'Phone number',fulfilment:'Order type',delivery:'Delivery',takeaway:'Takeaway',dinein:'Dine-in',payment:'Payment method',whatsappCod:'WhatsApp / Cash on delivery',availableNow:'Available now',gatewayPending:'Waiting for bank gateway credentials',orderValue:'Order total',sendWhatsapp:'Send order to branch WhatsApp',privacy:'Your order is sent only to the branch you select.',all:'All',meals:'Meals',bowls:'Bowls',wraps:'Wraps',extras:'Extras',drinks:'Drinks',add:'Add',empty:'Your cart is empty. Choose a meal to begin.',added:'Added to your cart',chooseFirst:'Add at least one item first',chooseBranch:'Choose branch',openMap:'Open location ↗',newOrder:'New order - Affandi Chicken Dubai',customer:'Customer',branch:'Branch',receipt:'Order type',payMethod:'Payment',orderTotal:'Total'}
};
I18N.ar.add='اطلب';
I18N.en.add='Order';
const branches=[
{id:'dubai',ar:'دبي',en:'Dubai',phone:'971528666619',display:'052 866 6619',map:'https://maps.app.goo.gl/TgLsfQvtVpJHdTkt8?g_st=ic'},
{id:'majaz',ar:'المجاز 1',en:'Al Majaz 1',phone:'971555570560',display:'055 557 0560',map:'https://maps.app.goo.gl/uVXgZeUQVsB3db3t8?g_st=ic'},
{id:'taawun',ar:'الشارقة - التعاون',en:'Sharjah - Al Taawun',phone:'971564087870',display:'056 408 7870',map:'https://maps.google.com/?q=25.309641,55.372841'},
{id:'marsa',ar:'عجمان - مرسى عجمان',en:'Ajman - Marsa Ajman',phone:'971564088288',display:'056 408 8288',map:'https://maps.google.com/?q=25.421204,55.443203'},
{id:'khalifa',ar:'عجمان - شارع خليفة',en:'Ajman - Khalifa Street',phone:'971554505712',display:'055 450 5712',map:'https://maps.app.goo.gl/QiVmUfQxMzwx8WG16?g_st=awb'}];
const products=[
{id:'spicy-broasted',ar:'بروستد حار – ٤ قطع',en:'Spicy Broasted – 4 Pieces',arDesc:'بطاطا، خبز، مخلل، كريم توم حار، كولسلو وكاتشب',enDesc:'Fries, bread, pickles, spicy garlic cream, coleslaw and ketchup',price:32,cat:'meals',tag:'SPICY',image:'https://chicken-dubai-clone.lovable.app/assets/spicy-broasted.webp'},
{id:'cheddar-jalapeno-fries',ar:'بطاطا مع جبنة شيدر وهالبينو',en:'Cheddar Jalapeño Fries',arDesc:'بطاطا، جبنة شيدر، هالبينو، كريم توم، مخلل وكاتشب',enDesc:'Fries, cheddar cheese, jalapeño, garlic cream, pickles and ketchup',price:22,cat:'extras',tag:'LOADED',image:'https://chicken-dubai-clone.lovable.app/assets/cheddar-jalapeno-fries.webp'},
{id:'zinger-burger',ar:'برجر زنجر',en:'Zinger Burger',arDesc:'كريم توم، مخلل وكاتشب',enDesc:'Garlic cream, pickles and ketchup',price:23,cat:'meals',tag:'CRISPY',image:'https://chicken-dubai-clone.lovable.app/assets/zinger-burger.webp'},
{id:'chicken-burger',ar:'برجر دجاج',en:'Chicken Burger',arDesc:'مخلل، كريم توم وكاتشب',enDesc:'Pickles, garlic cream and ketchup',price:18,cat:'meals',tag:'CLASSIC',image:'https://chicken-dubai-clone.lovable.app/assets/chicken-burger.webp'},
{id:'shish-sandwich',ar:'ساندوتش شيش',en:'Shish Tawook Sandwich',arDesc:'مخلل، كريم توم وكاتشب',enDesc:'Pickles, garlic cream and ketchup',price:16,cat:'wraps',tag:'GRILLED',image:'https://chicken-dubai-clone.lovable.app/assets/shish-sandwich.webp'},
{id:'hummus',ar:'حمص',en:'Hummus',arDesc:'حمص كريمي مع زيت الزيتون',enDesc:'Creamy hummus with olive oil',price:7,cat:'extras',tag:'FRESH',image:'https://chicken-dubai-clone.lovable.app/assets/hummus.webp'},
{id:'mutabbal',ar:'متبل',en:'Mutabbal',arDesc:'متبل كريمي مع زيت الزيتون',enDesc:'Creamy mutabbal with olive oil',price:7,cat:'extras',tag:'FRESH',image:'https://chicken-dubai-clone.lovable.app/assets/mutabbal.webp'},
{id:'golden-burger',ar:'جولدن برجر',en:'Golden Burger',arDesc:'بطاطا، كريم توم، كريم توم حار، كولسلو، كاتشب ومخلل',enDesc:'Fries, garlic cream, spicy garlic cream, coleslaw, ketchup and pickles',price:34,cat:'meals',tag:'GOLDEN',image:'https://chicken-dubai-clone.lovable.app/assets/golden-burger.webp'},
{id:'vista',ar:'فيستا',en:'Vista',arDesc:'بطاطا، جبنة، صوص منوّع وكاتشب',enDesc:'Fries, cheese, assorted sauces and ketchup',price:32,cat:'bowls',tag:'SAUCY',image:'https://chicken-dubai-clone.lovable.app/assets/vista.webp'},
{id:'musahab',ar:'دجاج مسحب',en:'Boneless Chicken',arDesc:'رز أو بطاطا، كريم توم، كولسلو، حمص ومخلل',enDesc:'Rice or fries, garlic cream, coleslaw, hummus and pickles',price:32,cat:'meals',tag:'GRILLED',image:'https://chicken-dubai-clone.lovable.app/assets/chicken-musahab.webp'},
{id:'kebab',ar:'كباب دجاج – ٣ أسياخ',en:'Chicken Kebab – 3 Skewers',arDesc:'رز أو بطاطا، كريم توم، كولسلو، مخلل، حمص وكاتشب',enDesc:'Rice or fries, garlic cream, coleslaw, pickles, hummus and ketchup',price:32,cat:'meals',tag:'GRILLED',image:'https://chicken-dubai-clone.lovable.app/assets/chicken-kebab.webp'},
{id:'shish',ar:'شيش طاووق – ٣ أسياخ',en:'Shish Tawook – 3 Skewers',arDesc:'رز أو بطاطا، كريم توم، كولسلو، مخلل، حمص وكاتشب',enDesc:'Rice or fries, garlic cream, coleslaw, pickles, hummus and ketchup',price:30,cat:'meals',tag:'JUICY',image:'https://chicken-dubai-clone.lovable.app/assets/shish-tawook.webp'},
{id:'special-grilled',ar:'وجبة سبيشل مشوي',en:'Special Grilled Meal',arDesc:'رز، صوص كبسة ومخلل',enDesc:'Rice, kabsa sauce and pickles',price:25,cat:'meals',tag:'SPECIAL',image:'https://chicken-dubai-clone.lovable.app/assets/special-grilled.webp'},
{id:'rizo',ar:'ريزو دجاج',en:'Chicken Rizo',arDesc:'رز أو بطاطا، كاتشب وكولسلو',enDesc:'Rice or fries, ketchup and coleslaw',price:32,cat:'bowls',tag:'LOADED',image:'https://chicken-dubai-clone.lovable.app/assets/chicken-rizo.webp'},
{id:'bbq-wrap',ar:'راب باربكيو',en:'BBQ Wrap',arDesc:'راب دجاج مقرمش مع بطاطا وصوص باربكيو',enDesc:'Crispy chicken wrap with fries and barbecue sauce',price:19,cat:'wraps',tag:'BBQ',image:'https://chicken-dubai-clone.lovable.app/assets/bbq-wrap.webp'},
{id:'buffalo-wrap',ar:'راب بافلو',en:'Buffalo Wrap',arDesc:'راب دجاج مقرمش مع بطاطا وصوص بافلو',enDesc:'Crispy chicken wrap with fries and buffalo sauce',price:21,cat:'wraps',tag:'SPICY',image:'https://chicken-dubai-clone.lovable.app/assets/buffalo-wrap.webp'},
{id:'classic-wrap',ar:'راب كلاسيك',en:'Classic Wrap',arDesc:'راب دجاج مقرمش مع بطاطا',enDesc:'Crispy chicken wrap with fries',price:18,cat:'wraps',tag:'CLASSIC',image:'https://chicken-dubai-clone.lovable.app/assets/classic-wrap.webp'},
{id:'chicken-nuggets',ar:'ناجت دجاج – ٨ قطع',en:'Chicken Nuggets – 8 Pieces',arDesc:'كريم توم، خبز، بطاطا، كولسلو ومخلل',enDesc:'Garlic cream, bread, fries, coleslaw and pickles',price:28,cat:'meals',tag:'CRISPY',image:'https://chicken-dubai-clone.lovable.app/assets/chicken-nuggets.webp'},
{id:'grilled-wings',ar:'جوانح مشوية',en:'Grilled Wings',arDesc:'خبز، كريم توم، مخلل، حمص، كولسلو وكاتشب',enDesc:'Bread, garlic cream, pickles, hummus, coleslaw and ketchup',price:35,cat:'meals',tag:'GRILLED',image:'https://chicken-dubai-clone.lovable.app/assets/grilled-wings.webp'},
{id:'afandi-tenders',ar:'تندر الأفندي',en:'Al Afandi Tenders',arDesc:'بطاطا، كريم توم، خبز، كولسلو، كاتشب وحمص',enDesc:'Fries, garlic cream, bread, coleslaw, ketchup and hummus',price:30,cat:'meals',tag:'SIGNATURE',image:'https://chicken-dubai-clone.lovable.app/assets/afandi-tenders.webp'},
{id:'crispy-shrimp',ar:'روبيان – ١٠ قطع',en:'Crispy Shrimp – 10 Pieces',arDesc:'بطاطا، كريم توم، كولسلو، خبز، مخلل وكاتشب',enDesc:'Fries, garlic cream, coleslaw, bread, pickles and ketchup',price:35,cat:'meals',tag:'SEAFOOD',image:'https://chicken-dubai-clone.lovable.app/assets/crispy-shrimp.webp'},
{id:'crispy-chicken',ar:'كرسبي – ٥ قطع',en:'Crispy Chicken – 5 Pieces',arDesc:'بطاطا، خبز، مخلل، كريم توم، كولسلو وكاتشب',enDesc:'Fries, bread, pickles, garlic cream, coleslaw and ketchup',price:32,cat:'meals',tag:'CRUNCH',image:'https://chicken-dubai-clone.lovable.app/assets/crispy-chicken.webp'},
{id:'regular-broasted',ar:'بروستد عادي – ٤ قطع',en:'Regular Broasted – 4 Pieces',arDesc:'بطاطا، خبز، مخلل، كريم توم، كولسلو وكاتشب',enDesc:'Fries, bread, pickles, garlic cream, coleslaw and ketchup',price:32,cat:'meals',tag:'BROASTED',image:'https://chicken-dubai-clone.lovable.app/assets/regular-broasted.webp'},
{id:'fish',ar:'وجبة فيليه السمك',en:'Fish Fillet Meal',arDesc:'فيليه سمك، بطاطا، خبز، كريم توم، كولسلو ومخلل',enDesc:'Fish fillet, fries, bread, garlic cream, coleslaw and pickles',price:35,cat:'meals',tag:'NEW',image:'https://chicken-dubai-clone.lovable.app/assets/fish-fillet-hero.webp',featured:true},
{id:'rice-plate',ar:'صحن رز',en:'Rice Plate',arDesc:'رز مع صوص كبسة',enDesc:'Rice with kabsa sauce',price:12,cat:'extras',tag:'SIDE',image:'https://chicken-dubai-clone.lovable.app/assets/rice-plate.webp'},
{id:'large-fries-plate',ar:'صحن بطاطا أصابع كبير',en:'Large French Fries Plate',arDesc:'مع كاتشب وكريم توم',enDesc:'With ketchup and garlic cream',price:16,cat:'extras',tag:'LARGE',image:'https://chicken-dubai-clone.lovable.app/assets/large-fries-plate.webp'},
{id:'fries',ar:'صحن بطاطا أصابع صغير',en:'Small French Fries Plate',arDesc:'مع كاتشب وكريم توم',enDesc:'With ketchup and garlic cream',price:8,cat:'extras',tag:'SMALL',image:'https://chicken-dubai-clone.lovable.app/assets/small-fries-plate.webp'},
{id:'sliced-potatoes',ar:'صحن بطاطا شرحات',en:'Sliced Potato Plate',arDesc:'مع كاتشب وكريم توم',enDesc:'With ketchup and garlic cream',price:20,cat:'extras',tag:'CRISPY',image:'https://chicken-dubai-clone.lovable.app/assets/sliced-potatoes.webp'},
{id:'honey-coleslaw',ar:'سلطة ملفوف بالعسل',en:'Honey Coleslaw',arDesc:'سلطة ملفوف كريمية بالعسل',enDesc:'Creamy honey coleslaw',price:5,cat:'extras',tag:'FRESH',image:'https://chicken-dubai-clone.lovable.app/assets/honey-coleslaw.webp'},
{id:'secret-sauce',ar:'صوص الأفندي السري',en:'Al Afandi Secret Sauce',arDesc:'صوص أفندي الكريمي الخاص',enDesc:'Al Afandi signature creamy sauce',price:3,cat:'extras',tag:'SIGNATURE',image:'https://chicken-dubai-clone.lovable.app/assets/secret-sauce.webp'},
{id:'dynamite-sauce',ar:'صوص دايناميت',en:'Dynamite Sauce',arDesc:'صوص كريمي بنكهة حارة',enDesc:'Creamy sauce with a spicy kick',price:3,cat:'extras',tag:'SPICY',image:'https://chicken-dubai-clone.lovable.app/assets/dynamite-sauce.webp'},
{id:'cheddar-sauce',ar:'جبنة شيدر',en:'Cheddar Cheese',arDesc:'صوص جبنة شيدر كريمي',enDesc:'Creamy cheddar cheese sauce',price:3,cat:'extras',tag:'CHEESY',image:'https://chicken-dubai-clone.lovable.app/assets/cheddar-sauce.webp'},
{id:'cocktail-sauce',ar:'صوص كوكتيل',en:'Cocktail Sauce',arDesc:'صوص كوكتيل كريمي',enDesc:'Creamy cocktail sauce',price:3,cat:'extras',tag:'SAUCE',image:'https://chicken-dubai-clone.lovable.app/assets/cocktail-sauce.webp'},
{id:'garlic',ar:'كريم توم',en:'Garlic Cream',arDesc:'صوص ثوم كريمي',enDesc:'Creamy garlic sauce',price:4,cat:'extras',tag:'PAIR IT',image:'https://raw.githubusercontent.com/balmyoutlet-prog/afandi-chicken-dubai/main/assets/garlic-cream.png'},
{id:'coleslaw',ar:'كولسلو',en:'Coleslaw',arDesc:'طازج وكريمي',enDesc:'Fresh and creamy',price:6,cat:'extras',tag:'FRESH'},

{id:'water',ar:'مياه',en:'Water',arDesc:'مياه شرب معبأة',enDesc:'Bottled drinking water',price:3,cat:'drinks',tag:'COLD',image:'https://chicken-dubai-clone.lovable.app/assets/water.png'},
{id:'kinza-lemon',ar:'كينزا ليمون',en:'Kinza Lemon',arDesc:'مشروب غازي بنكهة الليمون',enDesc:'Lemon flavoured soft drink',price:3,cat:'drinks',tag:'COLD',image:'https://chicken-dubai-clone.lovable.app/assets/kinza-lemon.png'},
{id:'kinza-orange',ar:'كينزا برتقال',en:'Kinza Orange',arDesc:'مشروب غازي بنكهة البرتقال',enDesc:'Orange flavoured soft drink',price:3,cat:'drinks',tag:'COLD',image:'https://chicken-dubai-clone.lovable.app/assets/kinza-orange.png'},
{id:'kinza-cola',ar:'كينزا كولا',en:'Kinza Cola',arDesc:'مشروب غازي كولا',enDesc:'Cola soft drink',price:3,cat:'drinks',tag:'COLD',image:'https://chicken-dubai-clone.lovable.app/assets/kinza-cola.png'},
{id:'mirinda',ar:'ميرندا',en:'Mirinda',arDesc:'مشروب غازي بنكهة البرتقال',enDesc:'Orange soft drink',price:3,cat:'drinks',tag:'COLD',image:'https://chicken-dubai-clone.lovable.app/assets/mirinda.png'},
{id:'mountain-dew',ar:'ماونتن ديو',en:'Mountain Dew',arDesc:'مشروب غازي منعش',enDesc:'Refreshing soft drink',price:3,cat:'drinks',tag:'COLD',image:'https://chicken-dubai-clone.lovable.app/assets/mountain-dew.png'},
{id:'7up-diet',ar:'سفن أب دايت',en:'7UP Diet',arDesc:'مشروب غازي بدون سكر',enDesc:'Zero sugar soft drink',price:3,cat:'drinks',tag:'COLD',image:'https://chicken-dubai-clone.lovable.app/assets/7up-diet.png'},
{id:'7up',ar:'سفن أب',en:'7UP',arDesc:'ليمون وليمون أخضر منعش',enDesc:'Refreshing lemon & lime',price:3,cat:'drinks',tag:'COLD',image:'https://chicken-dubai-clone.lovable.app/assets/7up.png'},
{id:'pepsi-diet',ar:'بيبسي دايت',en:'Pepsi Diet',arDesc:'كولا بدون سكر',enDesc:'Diet cola',price:3,cat:'drinks',tag:'COLD',image:'https://chicken-dubai-clone.lovable.app/assets/pepsi-diet.png'},
{id:'pepsi',ar:'بيبسي',en:'Pepsi',arDesc:'كولا كلاسيكية',enDesc:'Classic cola',price:3,cat:'drinks',tag:'COLD',image:'https://chicken-dubai-clone.lovable.app/assets/pepsi.png'}];
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
let lang=localStorage.getItem('affandi-lang-v2')||'ar',activeCategory='all',cart={};
const t=k=>I18N[lang][k]||k,money=n=>`AED ${Number(n).toFixed(0)}`,productName=p=>p[lang],productDesc=p=>p[`${lang}Desc`],branchName=b=>b[lang];
function applyLanguage(next,remember=false){lang=next;if(remember){localStorage.setItem('affandi-lang-v2',lang);localStorage.setItem('affandi-language-seen-v2','1')}document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';$('#languageSwitch').textContent=lang==='ar'?'EN':'ع';$$('[data-i18n]').forEach(el=>el.innerHTML=t(el.dataset.i18n));$('#customerName').placeholder=lang==='ar'?'مثال: محمد أسامة':'e.g. Mohammed Osama';$('#customerPhone').placeholder='05X XXX XXXX';renderFilters();renderMenu();renderBranches();renderCart();if($('#languageGate').open)$('#languageGate').close()}
function renderFilters(){const cats=['all','meals','bowls','wraps','extras','drinks'];$('#filters').innerHTML=cats.map(c=>`<button class="${c===activeCategory?'active':''}" data-cat="${c}">${t(c)}</button>`).join('');$$('#filters button').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.cat;renderFilters();renderMenu()})}
function renderMenu(){const list=activeCategory==='all'?products:products.filter(p=>p.cat===activeCategory);$('#menuGrid').innerHTML=list.map(p=>{const isDrink=p.cat==='drinks';return `<article class="menu-card ${p.featured?'featured':''} ${isDrink?'drink-card':''}"><div class="food-image">${p.image?`<img src="${p.image}" alt="${productName(p)}" loading="lazy">`:`<div class="food-placeholder">${p.en.split(' ')[0]}</div>`}${isDrink?'':`<span class="badge">${p.tag}</span>`}</div><div class="menu-card-body"><h3>${productName(p)}</h3>${isDrink?'':`<p>${productDesc(p)}</p>`}<div class="card-foot"><span class="price">${money(p.price)}</span><button class="add-button" data-add="${p.id}" aria-label="${t('add')} ${productName(p)}">${t('add')} +</button></div></div></article>`}).join('');$$('[data-add]').forEach(b=>b.onclick=()=>addItem(b.dataset.add))}
function addItem(id){cart[id]=(cart[id]||0)+1;renderCart();showToast(t('added'))}
function changeQty(id,d){cart[id]=(cart[id]||0)+d;if(cart[id]<=0)delete cart[id];renderCart()}
function totals(){return Object.entries(cart).reduce((sum,[id,q])=>sum+products.find(p=>p.id===id).price*q,0)}
function renderCart(){const entries=Object.entries(cart),count=entries.reduce((sum,[,q])=>sum+q,0);$('#cartCount').textContent=count;$('#cartTotal').textContent=money(totals());$('#checkoutTotal').textContent=money(totals());$('#cartItems').innerHTML=entries.length?entries.map(([id,q])=>{const p=products.find(x=>x.id===id);return `<div class="cart-line"><div><strong>${productName(p)}</strong><span>${money(p.price*q)}</span></div><div class="quantity"><button data-minus="${id}" aria-label="minus">−</button><b>${q}</b><button data-plus="${id}" aria-label="plus">+</button></div></div>`}).join(''):`<div class="empty-cart">${t('empty')}</div>`;$$('[data-minus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.minus,-1));$$('[data-plus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.plus,1));renderRecommendations(entries.map(([id])=>id))}
function renderRecommendations(ids){const rec=[];if(ids.length&&!ids.includes('garlic'))rec.push(products.find(p=>p.id==='garlic'));if(ids.length&&!ids.includes('water'))rec.push(products.find(p=>p.id==='water'));if(ids.length&&!ids.includes('fries'))rec.push(products.find(p=>p.id==='fries'));$('#recommendations').hidden=!rec.length;$('#recommendationList').innerHTML=rec.map(p=>`<div class="recommendation-item"><span>${productName(p)} <b>${money(p.price)}</b></span><button class="mini-add" data-rec="${p.id}">${t('add')}</button></div>`).join('');$$('[data-rec]').forEach(b=>b.onclick=()=>addItem(b.dataset.rec))}
function renderBranches(){$('#branchGrid').innerHTML=branches.map(b=>`<article class="branch-card"><h3>${branchName(b)}</h3><a href="tel:+${b.phone}">${b.display}</a><a href="${b.map}" target="_blank" rel="noopener">${t('openMap')}</a></article>`).join('');$('#branchSelect').innerHTML=`<option value="">${t('chooseBranch')}</option>`+branches.map(b=>`<option value="${b.id}">${branchName(b)} — ${b.display}</option>`).join('')}
function openCart(){$('#drawerBackdrop').hidden=false;$('#cartDrawer').classList.add('open');$('#cartDrawer').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeCart(){$('#drawerBackdrop').hidden=true;$('#cartDrawer').classList.remove('open');$('#cartDrawer').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function openCheckout(){if(!Object.keys(cart).length)return showToast(t('chooseFirst'));closeCart();$('#checkoutDialog').showModal()}
function showToast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>$('#toast').classList.remove('show'),1800)}
function submitOrder(e){e.preventDefault();const branch=branches.find(b=>b.id===$('#branchSelect').value);if(!branch)return;const name=$('#customerName').value.trim(),phone=$('#customerPhone').value.trim(),mode=document.querySelector('[name="mode"]:checked')?.value;const lines=Object.entries(cart).map(([id,q])=>{const p=products.find(x=>x.id===id);return `• ${productName(p)} × ${q} — ${money(p.price*q)}`}).join('\n');const msg=`${t('newOrder')}\n\n${t('branch')}: ${branchName(branch)}\n${t('customer')}: ${name}\n${t('phone')}: ${phone}\n${t('receipt')}: ${mode}\n${t('payMethod')}: WhatsApp / COD\n\n${lines}\n\n${t('orderTotal')}: ${money(totals())}`;window.location.href=`https://wa.me/${branch.phone}?text=${encodeURIComponent(msg)}`}
$$('[data-language]').forEach(b=>b.onclick=()=>applyLanguage(b.dataset.language,true));$('#languageSwitch').onclick=()=>applyLanguage(lang==='ar'?'en':'ar',true);$('#openCartBtn').onclick=openCart;$('#closeCartBtn').onclick=closeCart;$('#drawerBackdrop').onclick=closeCart;$('#checkoutBtn').onclick=openCheckout;$('#closeCheckoutBtn').onclick=()=>$('#checkoutDialog').close();$('#branchQuickBtn').onclick=()=>$('#branches').scrollIntoView({behavior:'smooth'});$('#heroOrder').onclick=()=>{addItem('fish');openCart()};$('#checkoutForm').onsubmit=submitOrder;

/* ---- 2026 conversion redesign: quick view, upsells, sticky cart, microcopy ---- */
Object.assign(I18N.ar,{heroTitle:'قرمشة تسمعها.<br>وطعم ترجع له.',viewCart:'السلة',addToCart:'أضف إلى السلة',quantity:'الكمية',goesWell:'يناسبها',branchPicked:'تم اختيار الفرع ✓',orderReady:'طلبك جاهز للإرسال ✓',completeIt:'كمّل وجبتك',orderNow:'اطلب الآن'});
Object.assign(I18N.en,{heroTitle:'Hear the crunch.<br>Taste the difference.',viewCart:'Cart',addToCart:'Add to cart',quantity:'Quantity',goesWell:'Goes well with',branchPicked:'Branch selected ✓',orderReady:'Your order is ready to send ✓',completeIt:'Complete your meal',orderNow:'Order now'});
const UPSELL_IDS=['fries','honey-coleslaw','secret-sauce','pepsi','hummus','cheddar-jalapeno-fries','water'];
function upsellPool(exclude){return UPSELL_IDS.filter(id=>!exclude.includes(id)).map(id=>products.find(p=>p.id===id)).filter(Boolean)}
function cardHTML(p){const isDrink=p.cat==='drinks';return `<article class="menu-card ${p.featured?'featured':''} ${isDrink?'drink-card':''}"><div class="food-image" data-view="${p.id}" role="button" tabindex="0" aria-label="${productName(p)}">${p.image?`<img src="${p.image}" alt="${productName(p)}" loading="lazy">`:`<div class="food-placeholder">${p.en.split(' ')[0]}</div>`}${isDrink?'':`<span class="badge">${p.tag}</span>`}</div><div class="menu-card-body"><h3>${productName(p)}</h3>${isDrink?'':`<p>${productDesc(p)}</p>`}<div class="card-foot"><span class="price">${money(p.price)}</span><button class="add-button" data-add="${p.id}" aria-label="${t('add')} ${productName(p)}">${t('add')} +</button></div></div></article>`}
function bindCards(root){root.querySelectorAll('[data-add]').forEach(b=>b.onclick=e=>{e.stopPropagation();addItem(b.dataset.add)});root.querySelectorAll('[data-view]').forEach(el=>{el.onclick=()=>openQuickView(el.dataset.view);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openQuickView(el.dataset.view)}}})}
function renderMenu(){const list=activeCategory==='all'?products:products.filter(p=>p.cat===activeCategory);const grid=$('#menuGrid');grid.innerHTML=list.map(cardHTML).join('');bindCards(grid);renderUpsellRail();syncSticky()}
function renderUpsellRail(){const rail=$('#upsellRail');if(!rail)return;const picks=upsellPool(Object.keys(cart)).slice(0,6);const pool=picks.length>=5?picks:upsellPool([]).slice(0,6);rail.innerHTML=pool.map(p=>`<article class="upsell-card"><div class="upsell-image" data-view="${p.id}" role="button" tabindex="0" aria-label="${productName(p)}">${p.image?`<img src="${p.image}" alt="${productName(p)}" loading="lazy">`:`<div class="food-placeholder">${p.en.split(' ')[0]}</div>`}</div><h4>${productName(p)}</h4><div class="upsell-foot"><span>${money(p.price)}</span><button class="mini-add" data-add="${p.id}">+</button></div></article>`).join('');bindCards(rail)}
function renderCart(){const entries=Object.entries(cart),count=entries.reduce((sum,[,q])=>sum+q,0);$('#cartCount').textContent=count;$('#cartTotal').textContent=money(totals());$('#checkoutTotal').textContent=money(totals());$('#cartItems').innerHTML=entries.length?entries.map(([id,q])=>{const p=products.find(x=>x.id===id);return `<div class="cart-line"><div><strong>${productName(p)}</strong><span>${money(p.price*q)}</span></div><div class="quantity"><button data-minus="${id}" aria-label="minus">−</button><b>${q}</b><button data-plus="${id}" aria-label="plus">+</button></div></div>`}).join(''):`<div class="empty-cart">${t('empty')}</div>`;$$('[data-minus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.minus,-1));$$('[data-plus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.plus,1));renderRecommendations(entries.map(([id])=>id));renderUpsellRail();syncSticky()}
function renderRecommendations(ids){const rec=upsellPool(ids).slice(0,5);const box=$('#recommendations');box.hidden=!ids.length||!rec.length;$('#recommendationList').innerHTML=rec.map(p=>`<div class="recommendation-item"><span>${productName(p)} <b>${money(p.price)}</b></span><button class="mini-add" data-rec="${p.id}">${t('add')}</button></div>`).join('');$$('[data-rec]').forEach(b=>b.onclick=()=>addItem(b.dataset.rec))}
function syncSticky(){const count=Object.values(cart).reduce((s,q)=>s+q,0),bar=$('#stickyBar');if(!bar)return;bar.classList.toggle('show',count>0);$('#stickyCount').textContent=count;$('#stickyTotal').textContent=money(totals())}
let qvId=null,qvQty=1;
function openQuickView(id){const p=products.find(x=>x.id===id);if(!p)return;qvId=id;qvQty=1;$('#qvImage').src=p.image||'/assets/affandi-logo.jpeg';$('#qvImage').alt=productName(p);$('#qvName').textContent=productName(p);$('#qvPrice').textContent=money(p.price);$('#qvQty').textContent=qvQty;$('#qvAdd').textContent=t('addToCart');$('#qvUpsellTitle').textContent=t('goesWell');const rec=upsellPool([id]).slice(0,5);$('#qvUpsell').innerHTML=rec.map(x=>`<button class="qv-chip" data-qvadd="${x.id}">${x.image?`<img src="${x.image}" alt="${productName(x)}">`:''}<span>${productName(x)}</span><b>${money(x.price)}</b></button>`).join('');$('#qvUpsell').querySelectorAll('[data-qvadd]').forEach(b=>b.onclick=()=>addItem(b.dataset.qvadd));const d=$('#quickView');if(!d.open)d.showModal()}
function qvChange(d){qvQty=Math.max(1,qvQty+d);$('#qvQty').textContent=qvQty}
$('#qvClose').onclick=()=>$('#quickView').close();
$('#qvMinus').onclick=()=>qvChange(-1);
$('#qvPlus').onclick=()=>qvChange(1);
$('#qvAdd').onclick=()=>{if(!qvId)return;cart[qvId]=(cart[qvId]||0)+qvQty;renderCart();showToast(t('added'));$('#quickView').close()};
$('#quickView').addEventListener('click',e=>{if(e.target.id==='quickView')$('#quickView').close()});
$('#stickyCheckout').onclick=openCart;
$('#heroCart').onclick=openCart;
$('#branchSelect').addEventListener('change',e=>{if(e.target.value)showToast(t('branchPicked'))});
$('#checkoutBtn').onclick=()=>{if(!Object.keys(cart).length)return showToast(t('chooseFirst'));closeCart();$('#checkoutDialog').showModal();showToast(t('orderReady'))};

/* ---- conversion flow: auto-open cart, cart upsells, checkout suggestions, bottom nav ---- */
Object.assign(I18N.ar,{completeOrderTitle:'كمّل طلبك',backToMenu:'العودة للمنيو',completeOrder:'إكمال الطلب',gDrinks:'المشروبات',gApps:'المقبلات',gSalads:'السلطات',gMatch:'يناسب طلبك',navHome:'الرئيسية',navMenu:'المنيو',navCart:'السلة',navAccount:'حسابي',accountSoon:'حسابك قريباً',accountBody:'تتبع طلباتك وعناوينك المفضلة — قادم مع حسابك.',closeLbl:'إغلاق'});
Object.assign(I18N.en,{completeOrderTitle:'Complete your order',backToMenu:'Back to menu',completeOrder:'Complete order',gDrinks:'Drinks',gApps:'Appetizers',gSalads:'Salads',gMatch:'Matches your order',navHome:'Home',navMenu:'Menu',navCart:'Cart',navAccount:'My account',accountSoon:'Coming with your account',accountBody:'Track your orders and saved addresses — coming with your account.',closeLbl:'Close'});

const GROUPS=[
{key:'gDrinks',ids:['pepsi','7up','mirinda','water','mountain-dew','kinza-cola']},
{key:'gApps',ids:['fries','cheddar-jalapeno-fries','sliced-potatoes','large-fries-plate','rice-plate','chicken-nuggets']},
{key:'gSalads',ids:['honey-coleslaw','coleslaw','hummus','mutabbal']},
{key:'gMatch',ids:['garlic','secret-sauce','dynamite-sauce','cheddar-sauce','cocktail-sauce']}];
const byId=id=>products.find(p=>p.id===id);
function contextualIds(){const ids=Object.keys(cart),cats=ids.map(id=>byId(id)?.cat);const main=cats.some(c=>c==='meals'||c==='wraps'||c==='bowls');const hasDrink=cats.includes('drinks');const order=[];if(main){order.push('garlic','fries','secret-sauce')}if(!hasDrink)order.unshift('pepsi');order.push('honey-coleslaw','cheddar-jalapeno-fries','hummus','water','7up','sliced-potatoes');return [...new Set(order)].filter(id=>!ids.includes(id)&&byId(id))}
function bigCard(p){return `<div class="co-card"><div class="co-img" data-view="${p.id}" role="button" tabindex="0" aria-label="${productName(p)}">${p.image?`<img src="${p.image}" alt="${productName(p)}" loading="lazy">`:`<div class="food-placeholder">${p.en.split(' ')[0]}</div>`}</div><div class="co-foot"><span class="co-name" data-view="${p.id}" role="button" tabindex="0">${productName(p)}</span><button class="mini-add" data-add="${p.id}" aria-label="${t('add')} ${productName(p)}">+</button></div></div>`}
function renderCartUpsell(){const box=$('#cartUpsell');if(!box)return;const picks=contextualIds().slice(0,3).map(byId);box.hidden=!Object.keys(cart).length||picks.length<1;$('#cartUpsellTitle').textContent=t('completeOrderTitle');$('#cartUpsellList').innerHTML=picks.map(bigCard).join('');bindCards(box)}
function renderCheckoutSuggest(){const box=$('#checkoutSuggest');if(!box)return;const inCart=Object.keys(cart);box.innerHTML=GROUPS.map(g=>{const items=g.ids.filter(id=>!inCart.includes(id)).map(byId).filter(Boolean).slice(0,6);if(!items.length)return '';return `<section class="cs-group"><h4>${t(g.key)}</h4><div class="cs-rail">${items.map(bigCard).join('')}</div></section>`}).join('');bindCards(box)}
function updateNav(){const c=Object.values(cart).reduce((s,q)=>s+q,0),b=$('#navCartCount');if(b){b.textContent=c;b.hidden=!c}$$('#bottomNav [data-nav-label]').forEach(el=>el.textContent=t(el.dataset.navLabel));$('#backToMenuBtn')&&($('#backToMenuBtn').textContent=t('backToMenu'));$('#checkoutBtn')&&($('#checkoutBtn').innerHTML=`<span>${t('completeOrder')}</span><i class="arrow">${lang==='ar'?'←':'→'}</i>`)}

(function buildUI(){
if(document.getElementById('bottomNav'))return;
const drawer=$('#cartDrawer'),total=drawer.querySelector('.cart-total'),rec=$('#recommendations');
if(rec)rec.hidden=true,rec.style.display='none';
const up=document.createElement('section');up.id='cartUpsell';up.className='cart-upsell';up.hidden=true;
up.innerHTML='<h3 id="cartUpsellTitle"></h3><div id="cartUpsellList" class="cart-upsell-list"></div>';
drawer.insertBefore(up,total);
const actions=document.createElement('div');actions.className='drawer-actions';
const back=document.createElement('button');back.id='backToMenuBtn';back.className='ghost-action';back.onclick=closeCart;
const co=$('#checkoutBtn');actions.appendChild(back);drawer.appendChild(actions);actions.appendChild(co);
const cs=document.createElement('div');cs.id='checkoutSuggest';cs.className='checkout-suggest';
const form=$('#checkoutForm'),sum=form.querySelector('.checkout-summary');form.insertBefore(cs,sum);
const nav=document.createElement('nav');nav.id='bottomNav';nav.className='bottom-nav';
nav.innerHTML=['home','menu','cart','account'].map(k=>`<button data-navto="${k}"><span class="nav-ico" aria-hidden="true">${k==='home'?'⌂':k==='menu'?'☰':k==='cart'?'🛒':'☺'}</span><span data-nav-label="nav${k[0].toUpperCase()+k.slice(1)}"></span>${k==='cart'?'<b id="navCartCount" hidden>0</b>':''}</button>`).join('');
document.body.appendChild(nav);
const acc=document.createElement('dialog');acc.id='accountDialog';acc.className='account-dialog';
acc.innerHTML='<div class="acc-inner"><span class="micro">MY ACCOUNT</span><h3 id="accTitle"></h3><p id="accBody"></p><button class="primary wide" id="accClose"></button></div>';
document.body.appendChild(acc);
acc.querySelector('#accClose').onclick=()=>acc.close();
nav.querySelectorAll('[data-navto]').forEach(b=>b.onclick=()=>{const k=b.dataset.navto;
 if(k==='home'){closeCart();document.querySelector('.hero').scrollIntoView({behavior:'smooth'})}
 else if(k==='menu'){closeCart();$('#menu').scrollIntoView({behavior:'smooth'})}
 else if(k==='cart'){openCart()}
 else{$('#accTitle').textContent=t('accountSoon');$('#accBody').textContent=t('accountBody');$('#accClose').textContent=t('closeLbl');if(!acc.open)acc.showModal()}});
})();

const _renderCart=renderCart;
renderCart=function(){_renderCart();renderCartUpsell();renderCheckoutSuggest();updateNav()};
const _addItem=addItem;
addItem=function(id){_addItem(id);openCart()};
$('#qvAdd').onclick=()=>{if(!qvId)return;cart[qvId]=(cart[qvId]||0)+qvQty;renderCart();showToast(t('added'));$('#quickView').close();openCart()};
applyLanguage(lang);
if(!localStorage.getItem('affandi-language-seen-v2'))$('#languageGate').showModal();
