/* Private CRM/funnel. Reuses existing sessions; NEVER provisions users. */
export function createInsightsHandler({base,secret,fetcher=fetch}){
const enc=new TextEncoder(),prefix='afandi_dubai_',uuid=/^[\da-f]{8}-[\da-f]{4}-[1-5][\da-f]{3}-[89ab][\da-f]{3}-[\da-f]{12}$/i;
const allowed=new Set(['https://alafandichicken.com','https://www.alafandichicken.com','https://afandi-dubai-gateway.vercel.app']);
const hex=b=>[...new Uint8Array(b)].map(n=>n.toString(16).padStart(2,'0')).join('');
const check=(ok,code='INVALID_REQUEST',status=400)=>{if(!ok)throw Object.assign(new Error(code),{status});};
const equal=(a,b)=>{if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0;};
const sha=async v=>hex(await crypto.subtle.digest('SHA-256',enc.encode(v)));
const mac=async v=>{const k=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return hex(await crypto.subtle.sign('HMAC',k,enc.encode('afandi-dubai:'+v)));};
async function db(path,method='GET',body,prefer='return=representation'){const r=await fetcher(base+'/rest/v1/'+path,{method,headers:{apikey:secret,Authorization:'Bearer '+secret,'Content-Type':'application/json',Prefer:prefer},body:body===undefined?undefined:JSON.stringify(body)});check(r.ok,'SERVICE_UNAVAILABLE',503);const raw=await r.text();return raw?JSON.parse(raw):null;}
const table=(n,q='')=>prefix+n+(q?'?'+q:''),rpc=(n,p)=>db('rpc/'+prefix+n,'POST',p);
const cookies=req=>Object.fromEntries((req.headers.get('cookie')||'').split(';').map(x=>{const i=x.indexOf('=');return i<0?['','']:[x.slice(0,i).trim(),x.slice(i+1).trim()];}));
function cookie(out,n,v,age){out.push(`${n}=${v}; Path=/; Secure; HttpOnly; SameSite=Strict; Max-Age=${age}`);}
async function signed(req,n){const [id,exp,sig]=(cookies(req)[n]||'').split('.');return /^[a-f0-9]{64}$/.test(id||'')&&Number(exp)>Date.now()&&equal(sig,await mac(n+':'+id+':'+exp))?id:null;}
async function identity(req,out,create=false){let v=await signed(req,'__Host-afd_visitor'),s=await signed(req,'__Host-afd_session');if(!v&&!create)return null;async function make(n,age){const id=hex(crypto.getRandomValues(new Uint8Array(32))),exp=String(Date.now()+age*1000);cookie(out,n,id+'.'+exp+'.'+await mac(n+':'+id+':'+exp),age);return id;}if(!v)v=await make('__Host-afd_visitor',15552000);if(!s)s=await make('__Host-afd_session',1800);return {visitor_hash:await mac('visitor:'+v),session_hash:await mac('session:'+s)};}
async function admin(req){const token=cookies(req)['__Host-afd_admin'];check(/^[a-f0-9]{64}$/.test(token||''),'AUTH_REQUIRED',401);const s=(await db(table('sessions','token_hash=eq.'+await sha(token)+'&select=admin_id,expires_at,idle_expires_at&limit=1')))?.[0];check(s&&Date.parse(s.expires_at)>Date.now()&&Date.parse(s.idle_expires_at)>Date.now(),'AUTH_REQUIRED',401);const a=(await db(table('admins','id=eq.'+s.admin_id+'&select=id,must_change_password&limit=1')))?.[0];check(a,'AUTH_REQUIRED',401);check(!a.must_change_password,'PASSWORD_CHANGE_REQUIRED',403);return a;}
const text=(v,n=120)=>{check(typeof v==='string'&&v.length<=n&&!/[\u0000-\u001f]/.test(v));return v.trim();};
function dates(d){const f=text(d.from,10),t=text(d.to,10);check(/^\d{4}-\d{2}-\d{2}$/.test(f)&&/^\d{4}-\d{2}-\d{2}$/.test(t));const a=new Date(f+'T00:00:00+04:00'),b=new Date(t+'T00:00:00+04:00');check(Number.isFinite(+a)&&Number.isFinite(+b)&&+b>=+a&&+b-+a<3660*86400000);check(new Date(+a+14400000).toISOString().slice(0,10)===f&&new Date(+b+14400000).toISOString().slice(0,10)===t);return {p_from:a.toISOString(),p_to:new Date(+b+86400000).toISOString()};}
async function json(req){const reader=req.body?.getReader();if(!reader)return {};let parts=[],size=0;for(;;){const{value,done}=await reader.read();if(done)break;size+=value.length;if(size>8192){await reader.cancel();check(false,'REQUEST_TOO_LARGE',413);}parts.push(value);}const arr=new Uint8Array(size);let p=0;for(const part of parts){arr.set(part,p);p+=part.length;}try{return JSON.parse(new TextDecoder().decode(arr));}catch{check(false,'INVALID_JSON');}}
const clean=v=>String(v||'').replace(/[\u0000-\u001f<>]/g,'').slice(0,120);
function attribution(d){const a=d.attribution||{};let host='';try{host=new URL(a.referrer).hostname;}catch{}const source=clean(a.source).toLowerCase()||(/instagram/.test(host)?'instagram':/facebook/.test(host)?'facebook':/google\./.test(host)?'google':/tiktok/.test(host)?'tiktok':host||'direct');return {source,medium:clean(a.medium)||(source==='direct'?'none':source==='google'?'organic':'referral'),campaign:clean(a.campaign)};}
async function rate(req,key,limit=60){const ip=req.headers.get('cf-connecting-ip')||req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'unknown';check(await rpc('rate_limit',{p_key:await mac('insights:'+key+':'+ip),p_seconds:60,p_limit:limit}),'RATE_LIMITED',429);}
function response(data,status,out){const h=new Headers({'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Vary':'Cookie','X-Content-Type-Options':'nosniff','X-Robots-Tag':'noindex'});out.forEach(c=>h.append('Set-Cookie',c));return new Response(JSON.stringify(data),{status,headers:h});}
return async req=>{const out=[];try{check(base&&secret,'SERVICE_UNAVAILABLE',503);const path=new URL(req.url).pathname.split('/afandi-dubai-insights')[1]||'/',post=req.method==='POST';if(path==='/health'&&req.method==='GET')return response({ok:true,version:1},200,out);check(post,'METHOD_NOT_ALLOWED',405);const origin=req.headers.get('origin');check(allowed.has(origin),'ORIGIN_DENIED',403);check(req.headers.get('x-afandi-request')==='1'&&/^application\/json\b/i.test(req.headers.get('content-type')||''),'INVALID_REQUEST');
if(path.startsWith('/admin/')){await admin(req);const d=await json(req);if(path==='/admin/funnel')return response(await rpc('funnel_report',dates(d)),200,out);if(path==='/admin/customers'){const offset=d.offset??0;check(Number.isSafeInteger(offset)&&offset>=0&&offset<=1000000&&['recent','spend','orders'].includes(d.sort||'recent'));return response(await rpc('customer_list',{p_search:text(d.search||'',100),p_offset:offset,p_sort:d.sort||'recent'}),200,out);}if(path==='/admin/customer'){const phone=text(d.phone,16);check(/^[1-9]\d{7,14}$/.test(phone));const result=await rpc('customer_profile',{p_phone:phone,...dates(d)});check(result,'NOT_FOUND',404);return response(result,200,out);}check(false,'NOT_FOUND',404);}
const d=await json(req);
if(path==='/event'){if(d.analytics_consent!==true||d.test===true||req.headers.get('dnt')==='1'||req.headers.get('sec-gpc')==='1'||/bot|crawler|spider|headless|playwright/i.test(req.headers.get('user-agent')||''))return response({recorded:false},200,out);await rate(req,'events',90);check(uuid.test(d.event_id||'')&&['view_item','add_to_cart','begin_checkout'].includes(d.event_kind));const pid=d.event_kind==='begin_checkout'?null:text(d.product_id,80);let qty=null;if(pid){check(/^[a-z0-9][a-z0-9-]{0,79}$/.test(pid));const p=await db(table('products','id=eq.'+pid+'&active=eq.true&select=id&limit=1'));check(p?.length,'UNKNOWN_PRODUCT');}if(d.event_kind==='add_to_cart'){qty=d.quantity;check(Number.isSafeInteger(qty)&&qty>=1&&qty<=99);}const ids=await identity(req,out,true);await db(table('events','on_conflict=event_id'),'POST',{event_id:d.event_id,event_kind:d.event_kind,...ids,product_id:pid,quantity:qty,...attribution(d)},'resolution=ignore-duplicates,return=minimal');await db(table('settings','id=eq.true&funnel_started_at=is.null'),'PATCH',{funnel_started_at:new Date().toISOString()});return response({recorded:true},200,out);}
if(path==='/preferences'){check(typeof d.remember==='boolean');await rate(req,'preferences',12);const ids=await identity(req,out,d.remember);if(ids)await db(table('browser_preferences','on_conflict=visitor_hash'),'POST',{visitor_hash:ids.visitor_hash,remember:d.remember,updated_at:new Date().toISOString()},'resolution=merge-duplicates,return=minimal');return response({remember:d.remember},200,out);}
if(path==='/order-consent'){await rate(req,'consent',12);const ids=await identity(req,out);check(ids,'AUTH_REQUIRED',401);const reference=text(d.reference,40);check(/^AFD-[A-F0-9]{14}$/.test(reference)&&typeof d.marketing_opt_in==='boolean'&&typeof d.remember==='boolean');const o=(await db(table('orders','reference=eq.'+reference+'&visitor_hash=eq.'+ids.visitor_hash+'&select=id,created_at&limit=1')))?.[0];check(o&&Date.parse(o.created_at)>Date.now()-300000,'NOT_FOUND',404);await db(table('order_preferences','on_conflict=order_id'),'POST',{order_id:o.id,marketing_opt_in:d.marketing_opt_in,remember:d.remember},'resolution=ignore-duplicates,return=minimal');await db(table('browser_preferences','on_conflict=visitor_hash'),'POST',{visitor_hash:ids.visitor_hash,remember:d.remember,updated_at:new Date().toISOString()},'resolution=merge-duplicates,return=minimal');return response({recorded:true},200,out);}
if(path==='/recommendations'){await rate(req,'recommendations',30);const ids=await identity(req,out);const repeat=ids?await rpc('reorder_products',{p_visitor:ids.visitor_hash}):[];const cart=Array.isArray(d.cart)?d.cart.slice(0,50).filter(x=>typeof x==='string'&&/^[a-z0-9-]{1,80}$/.test(x)):[];const all=await db(table('products','active=eq.true&available=eq.true&select=id,name_ar,name_en,category,price_cents,image_url&order=sort_order.asc,id.asc&limit=1000'));const known=new Set([...cart,...repeat.map(p=>p.id)]),hasMeal=all.some(p=>cart.includes(p.id)&&['meals','bowls','wraps'].includes(p.category));const fresh=all.filter(p=>!known.has(p.id)).sort((a,b)=>Number(hasMeal&&['drinks','extras'].includes(b.category))-Number(hasMeal&&['drinks','extras'].includes(a.category)));const tryItems=[];for(const category of hasMeal?['drinks','extras','meals']:['meals','wraps','bowls']){const p=fresh.find(x=>x.category===category);if(p)tryItems.push(p);}return response({repeat:repeat.filter(p=>!cart.includes(p.id)),try:tryItems.slice(0,3),personalized:repeat.length>0,basis:repeat.length?'completed_orders_on_this_consented_browser':'menu_categories',identity_lookup:false},200,out);}
check(false,'NOT_FOUND',404);
}catch(e){return response({error:e.status?e.message:'SERVICE_UNAVAILABLE'},e.status||503,out);}};
}
