'use strict';
const fs=require('node:fs'),http=require('node:http'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium,webkit}=require('playwright');
const seed=JSON.parse(fs.readFileSync('backend/catalog.json','utf8'));let products=structuredClone(seed),saved=[],passwordChanged=false,requests=[],visits=0;
const report={at:new Date().toISOString(),scope:'Local browser regression using isolated in-memory API fixtures. No live customer data, messages or orders.',browsers:[],public:[]};
fs.mkdirSync('audit-results',{recursive:true});
const error=(res,status,code)=>{res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify({error:code}));};
const json=(res,d)=>{res.writeHead(200,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(d));};
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,'http://localhost:3100');if(u.pathname.startsWith('/api/')){let raw='';for await(const c of req)raw+=c;const d=raw?JSON.parse(raw):{};requests.push({path:u.pathname,query:u.search,body:d});
 if(u.pathname==='/api/menu')return json(res,{products:products.filter(p=>p.active),settings:{contact_email:'info@alafandichicken.com',delivery_fee_cents:300,timezone:'Asia/Dubai'}});
 if(u.pathname==='/api/visit'){visits++;return json(res,{recorded:true});}
 if(u.pathname==='/api/order'){const total=d.items.reduce((s,l)=>s+products.find(p=>p.id===l.id).price_cents*l.quantity,0)+(d.fulfilment==='Delivery'?300:0);assert.equal(total,d.expected_total_cents);assert.ok(d.items.every(x=>x.version>0&&x.quantity>=1&&x.quantity<=99));if(!/^05\d{8}$/.test(d.customer_phone))return error(res,400,'INVALID_PHONE');const o=saved.find(x=>x.key===d.idempotency_key);if(!o)saved.push({key:d.idempotency_key,total});return json(res,{reference:'AFD-LOCAL-TEST',status:'new',total_cents:total,whatsapp_url:'https://wa.me/971528666619?text='+encodeURIComponent('TEST ONLY; AED '+total/100)});}
 if(u.pathname==='/api/admin/login'){assert.equal(req.headers['x-afandi-request'],'1');res.setHeader('Set-Cookie','local_fixture=1; HttpOnly; SameSite=Strict; Path=/');return json(res,{username:'admin',must_change_password:true});}
 if(!req.headers.cookie?.includes('local_fixture=1'))return error(res,401,'AUTH_REQUIRED');
 if(u.pathname==='/api/admin/me')return json(res,{username:'admin',must_change_password:!passwordChanged});
 if(u.pathname==='/api/admin/password'){assert.ok(d.new_password.length>=15);passwordChanged=true;return json(res,{ok:true});}
 if(!passwordChanged)return error(res,403,'PASSWORD_CHANGE_REQUIRED');
 if(u.pathname==='/api/admin/report')return json(res,{from:u.searchParams.get('from')+'T00:00:00+04:00',to:u.searchParams.get('to')+'T23:59:59+04:00',coverage:{tracking_started_at:null,orders_started_at:null},metrics:{visitors:0,pageviews:0,orders:0,sales_cents:0,ordering_clients:0,completed_orders:0},lifetime:{orders:0,sales_cents:0},daily:[],sources:[],targets:[],devices:[]});
 if(u.pathname==='/api/admin/products'){if(req.method==='POST'){const i=products.findIndex(x=>x.id===d.id);if(i>=0)products[i]={...products[i],...d,version:d.version+1};else products.push({...d,version:1});return json(res,{product:d});}return json(res,{products});}
 if(u.pathname==='/api/admin/orders')return json(res,{orders:[],next_offset:50,has_more:false});
 if(u.pathname==='/api/admin/audit')return json(res,{entries:[]});
 if(u.pathname==='/api/admin/logout')return json(res,{ok:true});
 return error(res,404,'NOT_FOUND');}
 let p=u.pathname;if(p==='/')p='/index.html';if(p==='/admin'||p==='/admin/')p='/admin/index.html';const f=path.resolve('dist','.'+p);if(!f.startsWith(path.resolve('dist')+path.sep))return error(res,404,'NOT_FOUND');try{const data=fs.readFileSync(f);const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.ico':'image/x-icon'};res.writeHead(200,{'Content-Type':types[path.extname(f)]||'application/octet-stream'});res.end(data);}catch{return error(res,404,'NOT_FOUND');}});
(async()=>{await new Promise(r=>server.listen(3100,'127.0.0.1',r));
for(const [name,engine] of [['chromium',chromium],['webkit',webkit]]){products=structuredClone(seed);saved=[];requests=[];passwordChanged=false;const checks=[],errors=[];const b=await engine.launch(),c=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));let whatsapp='';await c.route('**/*',route=>{const u=new URL(route.request().url());if(u.hostname==='wa.me'){whatsapp=u.href;return route.fulfill({status:200,contentType:'text/html',body:'Intercepted local test. No message sent.'});}if(/insights|google-analytics/.test(u.hostname+u.pathname))return route.fulfill({status:204,body:''});return route.continue();});
try{await p.goto('http://127.0.0.1:3100/?client_test=1');await p.locator('[data-language="en"]').click();await p.waitForFunction(()=>document.querySelector('#menuGrid').children.length===45);assert.equal(await p.locator('html').getAttribute('lang'),'en');checks.push('45 English menu products');await p.locator('#languageSwitch').click();assert.equal(await p.locator('html').getAttribute('lang'),'ar');await p.locator('#languageSwitch').click();checks.push('Arabic / English switching');
for(const cat of ['meals','bowls','wraps','extras','drinks']){await p.locator(`[data-cat="${cat}"]`).click();assert.equal(await p.locator('#menuGrid .menu-card').count(),seed.filter(x=>x.category===cat).length);}await p.locator('[data-cat="all"]').click();checks.push('All five category filters');
await p.locator('#menuGrid [data-add="spicy-broasted"]').click();assert.equal(await p.locator('#cartCount').innerText(),'1');await p.locator('#cartItems [data-plus="spicy-broasted"]').click();assert.equal(await p.locator('#cartCount').innerText(),'2');checks.push('Add to cart and quantity controls');await p.locator('#checkoutBtn').click();await p.locator('#branchSelect').selectOption('dubai');await p.locator('#customerName').fill('LOCAL TEST — NOT SENT');await p.locator('#customerPhone').fill('0500000000');
for(const [mode,total]of [['Delivery','AED 67.00'],['Takeaway','AED 64.00'],['Dine-in','AED 64.00'],['Delivery','AED 67.00']]){await p.locator(`input[name="mode"][value="${mode}"]`).check();await p.waitForFunction(t=>document.querySelector('#checkoutTotal').textContent===t,total);assert.equal(await p.locator('#deliveryAddress').evaluate(x=>x.required),mode==='Delivery');}await p.locator('#deliveryAddress').fill('LOCAL TEST — NOT A REAL ADDRESS');checks.push('Delivery AED 3, dine-in and takeaway totals; conditional address validation');
await p.locator('#checkoutBackToMenu, #checkoutAddItems').click();assert.equal(await p.locator('#checkoutDialog').evaluate(x=>x.open),false);await p.locator('#menuGrid [data-add="water"]').click();await p.locator('#checkoutBtn').click();assert.equal(await p.locator('#checkoutTotal').innerText(),'AED 70.00');checks.push('Add more items preserves basket and delivery fee');await p.locator('#checkoutForm button[type="submit"]').click();await p.waitForURL('https://wa.me/**');assert.equal(saved.length,1);assert.equal(saved[0].total,7000);assert.ok(whatsapp.includes('971528666619'));checks.push('Server request contains product versions, exact cents and idempotency key; WhatsApp handoff intercepted');
await p.goto('http://127.0.0.1:3100/?client_test=1');await p.locator('#menuGrid .menu-card').first().waitFor();assert.equal(await p.locator('a[href="mailto:info@alafandichicken.com"]').count(),1);await p.locator('img').evaluateAll(imgs=>imgs.forEach(i=>i.loading='eager'));await p.waitForFunction(()=>[...document.images].filter(i=>i.getAttribute('src')).every(i=>i.complete),null,{timeout:15000});const broken=await p.locator('img').evaluateAll(imgs=>imgs.filter(i=>i.getAttribute('src')&&!i.naturalWidth).map(i=>i.src));assert.deepEqual(broken,[]);checks.push('All image sources decode; contact email present');await p.screenshot({path:`audit-results/${name}-client.png`,fullPage:true});
await p.goto('http://127.0.0.1:3100/admin');await p.locator('#loginPanel').waitFor({state:'visible'});await p.locator('[name=password]').fill('local-fixture-only');await p.locator('#loginForm button').click();await p.locator('#passwordPanel').waitFor({state:'visible'});assert.equal(await p.locator('#workspace').isVisible(),false);await p.locator('#passwordForm [name=next]').fill('local-fixture-password-only');await p.locator('#passwordForm [name=confirm]').fill('local-fixture-password-only');await p.locator('#passwordForm button').click();await p.locator('#workspace').waitFor();await p.locator('#metrics .metric').first().waitFor();assert.ok((await p.locator('#metrics').innerText()).includes('غير متوفّر'));checks.push('Admin forced password-change UI; unavailable history never shown as invented sales');
await p.locator('#monthDate').fill('2026-08');await p.locator('#monthDate').dispatchEvent('change');await p.waitForTimeout(200);assert.equal(await p.locator('#fromDate').inputValue(),'2026-08-01');assert.equal(await p.locator('#toDate').inputValue(),'2026-08-31');checks.push('Day and month filtering requests exact calendar ranges');
await p.locator('[data-tab=menu]').click();await p.locator('.product-card').first().waitFor();await p.locator('#newProduct').click();await p.locator('[name=name_ar]').fill('صنف اختبار محلي');await p.locator('[name=name_en]').fill('<img src=x onerror=window.injected=1>');await p.locator('[name=id]').fill('local-test-only');await p.locator('[name=price]').fill('12.50');await p.locator('[name=active]').uncheck();await p.locator('#saveProduct').click();await p.locator('#productDialog').waitFor({state:'hidden'});assert.equal(products.at(-1).price_cents,1250);assert.equal(products.at(-1).active,false);assert.equal(await p.evaluate(()=>window.injected),undefined);checks.push('Add/edit item form uses exact cents and escaped text; publish visibility controlled');await p.screenshot({path:`audit-results/${name}-admin-fixture.png`,fullPage:true});assert.deepEqual(errors,[]);checks.push('No browser JavaScript errors');
}catch(e){report.browsers.push({browser:name,checks,errors:[...errors,e.message],passed:false});await p.screenshot({path:`audit-results/${name}-failure.png`,fullPage:true}).catch(()=>{});throw e;}finally{if(!report.browsers.some(x=>x.browser===name))report.browsers.push({browser:name,checks,errors,passed:true});await b.close();fs.writeFileSync('audit-results/regression.json',JSON.stringify(report,null,2));}}
assert.equal(visits,0);for(const url of ['https://alafandichicken.com/','http://alafandichicken.com/','https://www.alafandichicken.com/']){try{const r=await fetch(url,{redirect:'manual',signal:AbortSignal.timeout(15000)});report.public.push({url,status:r.status,location:r.headers.get('location')});}catch(e){report.public.push({url,error:e.message});}}
fs.writeFileSync('audit-results/regression.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());
