'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const labels={new:'جديد / غير مؤكّد',confirmed:'مؤكّد',completed:'مكتمل',cancelled:'ملغى',refunded:'مسترد'};
const errors={AUTH_REQUIRED:'انتهت جلسة الدخول. يرجى تسجيل الدخول من جديد.',INVALID_LOGIN:'بيانات الدخول أو رمز التفعيل غير صحيحة.',PASSWORD_CHANGE_REQUIRED:'يجب تغيير كلمة المرور المؤقتة أولاً.',WEAK_PASSWORD:'استخدموا كلمة مرور مختلفة من 15 حرفاً على الأقل.',INVALID_PASSWORD:'كلمة المرور الحالية غير صحيحة.',RATE_LIMITED:'محاولات كثيرة. انتظروا 15 دقيقة ثم أعيدوا المحاولة.',PRODUCT_VERSION_CONFLICT:'عدّل شخص آخر هذا الصنف. أغلقوا النافذة وحدّثوا المنيو قبل إعادة التعديل.',INVALID_TRANSITION:'لا يمكن تغيير الطلب إلى هذه الحالة من حالته الحالية.',SERVICE_UNAVAILABLE:'تعذّر الاتصال بالخادم. لم يتم افتراض أي أرقام أو تأكيد الحفظ.',UPLOAD_FAILED:'تعذّر رفع الصورة. لم يتم حفظ الصنف.',IMAGE_TOO_LARGE:'الصورة تتجاوز الحد المسموح.',INVALID_REQUEST:'راجعوا الحقول المدخلة.',INVALID_DATE_RANGE:'راجعوا الفترة المطلوبة.',INVALID_IMAGE_URL:'رابط الصورة يجب أن يكون HTTPS صالحاً.'};
const money=n=>new Intl.NumberFormat('en-AE',{style:'currency',currency:'AED'}).format(Number(n)/100),number=n=>Number(n).toLocaleString('en-US');
function dateKey(d=new Date()){const p=Object.fromEntries(new Intl.DateTimeFormat('en',{timeZone:'Asia/Dubai',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d).map(x=>[x.type,x.value]));return `${p.year}-${p.month}-${p.day}`;}
const shortDate=s=>new Intl.DateTimeFormat('ar-AE',{timeZone:'Asia/Dubai',dateStyle:'medium',timeStyle:'short'}).format(new Date(s));
function notice(s,bad=false){$('#notice').textContent=s;$('#notice').hidden=!s;$('#notice').classList.toggle('bad',bad);}
function node(tag,value,cls){const e=document.createElement(tag);if(value!==undefined)e.textContent=value;if(cls)e.className=cls;return e;}
function rows(target,data,columns,empty='لا توجد سجلات للفترة المقاسة.'){const b=$(target);b.replaceChildren();if(!data?.length){const tr=node('tr'),td=node('td',empty,'empty');td.colSpan=columns.length;tr.append(td);b.append(tr);return;}for(const item of data){const tr=node('tr');for(const col of columns)tr.append(node('td',col(item)));b.append(tr);}}
let coverage=null,currentTab='dashboard',allProducts=[],edited=null,offset=0,lastReport=null;
let activation=new URLSearchParams(location.hash.slice(1)).get('activate')||'';
if(activation){$('#loginForm').elements.activation.value=activation;history.replaceState(null,'',location.pathname);}
async function api(path,data){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20000);try{const r=await fetch('/api/admin/'+path,{method:data===undefined?'GET':'POST',credentials:'same-origin',cache:'no-store',headers:data===undefined?{}:{'Content-Type':'application/json','X-Afandi-Request':'1'},body:data===undefined?undefined:JSON.stringify(data),signal:controller.signal});let d;try{d=await r.json();}catch{throw Error('SERVICE_UNAVAILABLE');}if(!r.ok){if(d.error==='AUTH_REQUIRED')signedOut();throw Error(d.error||'SERVICE_UNAVAILABLE');}return d;}finally{clearTimeout(timeout);}}
function explain(e){return errors[e.message]||'لم تكتمل العملية. تحققوا من الاتصال والبيانات وأعيدوا المحاولة.';}
function signedOut(){$('#workspace').hidden=true;$('#passwordPanel').hidden=true;$('#loginPanel').hidden=false;$('#logout').hidden=true;lastReport=null;$('#orderList').replaceChildren();$('#metrics').replaceChildren();}
function showPassword(){$('#workspace').hidden=true;$('#loginPanel').hidden=true;$('#passwordPanel').hidden=false;$('#logout').hidden=false;}
async function signedIn(){$('#loginPanel').hidden=true;$('#passwordPanel').hidden=true;$('#workspace').hidden=false;$('#logout').hidden=false;await refresh();}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,b=form.querySelector('button');b.disabled=true;notice('');try{const d=await api('login',{username:form.elements.username.value,password:form.elements.password.value,activation:form.elements.activation.value});if(d.must_change_password){$('#passwordForm').elements.current.value=form.elements.password.value;showPassword();}else await signedIn();form.elements.password.value='';form.elements.activation.value='';activation='';}catch(err){notice(explain(err),true);}finally{b.disabled=false;}};
$('#passwordForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('button');if(f.elements.next.value!==f.elements.confirm.value){notice('كلمتا المرور غير متطابقتين.',true);return;}b.disabled=true;try{await api('password',{current_password:f.elements.current.value,new_password:f.elements.next.value});f.reset();notice('تم تحديث كلمة المرور.');await signedIn();}catch(err){notice(explain(err),true);}finally{b.disabled=false;}};
$('#logout').onclick=async()=>{try{await api('logout',{});}catch{}signedOut();};$('#changePassword').onclick=showPassword;
function query(){return new URLSearchParams({from:$('#fromDate').value,to:$('#toDate').value}).toString();}
$('#fromDate').value=$('#toDate').value=dateKey();
$('#dateForm').onsubmit=e=>{e.preventDefault();offset=0;refresh();};
$$('[data-range]').forEach(b=>b.onclick=()=>{const now=new Date(),today=dateKey(now);let from=today,to=today;switch(b.dataset.range){case'yesterday':from=to=dateKey(new Date(+now-86400000));break;case'week':from=dateKey(new Date(+now-6*86400000));break;case'month':from=today.slice(0,8)+'01';break;case'all':{const starts=[coverage?.tracking_started_at,coverage?.orders_started_at].filter(Boolean).map(x=>new Date(x));from=starts.length?dateKey(new Date(Math.min(...starts))):today;break;}}$('#fromDate').value=from;$('#toDate').value=to;offset=0;refresh();});
$('#monthDate').onchange=()=>{const v=$('#monthDate').value;if(!v)return;const[y,m]=v.split('-').map(Number);$('#fromDate').value=v+'-01';$('#toDate').value=v+'-'+String(new Date(Date.UTC(y,m,0)).getUTCDate()).padStart(2,'0');offset=0;refresh();};
$$('[data-tab]').forEach(b=>b.onclick=()=>{currentTab=b.dataset.tab;$$('[data-tab]').forEach(x=>x.classList.toggle('selected',x===b));$$('.tab-panel').forEach(x=>x.hidden=x.id!==currentTab);$('#datePanel').hidden=!['dashboard','orders'].includes(currentTab);refresh();});
async function refresh(){try{if(currentTab==='dashboard')await dashboard();if(currentTab==='orders')await orders(true);if(currentTab==='menu')await menu();if(currentTab==='audit')await audit();$('#lastUpdated').textContent='آخر تحديث: '+shortDate(new Date().toISOString());}catch(err){notice(explain(err),true);if(currentTab==='dashboard')$('#metrics').replaceChildren(node('p','تعذّر تحميل الأرقام. القيم غير متوفرة وليست صفراً.'));}}
function metric(title,value,sub){const e=node('article',undefined,'metric');e.append(node('span',title),node('b',value),node('small',sub||''));$('#metrics').append(e);}
async function dashboard(){const d=await api('report?'+query());lastReport=d;coverage=d.coverage;notice('');const visitsKnown=coverage?.tracking_started_at&&Date.parse(d.to)>Date.parse(coverage.tracking_started_at),ordersKnown=coverage?.orders_started_at&&Date.parse(d.to)>Date.parse(coverage.orders_started_at);const m=d.metrics;$('#metrics').replaceChildren();metric('متصفحات فريدة',visitsKnown?number(m.visitors):'غير متوفّر','المتصفحات التي وافقت على القياس');metric('مشاهدات الصفحات',visitsKnown?number(m.pageviews):'غير متوفّر','الزيارات المسجّلة في الفترة');metric('طلبات مسجّلة',ordersKnown?number(m.orders):'غير متوفّر','لا يعني أنها مدفوعة أو وصلت WhatsApp');metric('صافي المبيعات',ordersKnown?money(m.sales_cents):'غير متوفّر','المكتمل فعلياً ناقص المسترد');metric('عملاء قدّموا طلبات',ordersKnown?number(m.ordering_clients):'غير متوفّر','أرقام هواتف مميّزة ضمن الطلبات');metric('طلبات مكتملة',ordersKnown?number(m.completed_orders):'غير متوفّر','حسب تاريخ تأكيد الإكمال');metric('إجمالي الطلبات الموثقة',coverage?.orders_started_at?number(d.lifetime.orders):'غير متوفّر','كل الفترة المسجّلة، خارج الفلتر');metric('إجمالي المبيعات الموثقة',coverage?.orders_started_at?money(d.lifetime.sales_cents):'غير متوفّر','كل الفترة المسجّلة، خارج الفلتر');$('#coverage').textContent=['بداية قياس الزيارات: '+(coverage?.tracking_started_at?shortDate(coverage.tracking_started_at):'لا توجد زيارة مقاسة بعد.'),'بداية سجل الطلبات: '+(coverage?.orders_started_at?shortDate(coverage.orders_started_at):'لم يبدأ السجل بعد.'),'الفترة السابقة لبداية التسجيل غير متوفرة. الاختبارات لا تُدرج في المبيعات.'].join('\n');rows('#dailyRows',d.daily,[r=>r.date_key,r=>number(r.visitors),r=>number(r.pageviews),r=>number(r.orders),r=>money(r.sales_cents)]);rows('#sourceRows',d.sources,[r=>r.source,r=>r.medium,r=>r.campaign||'—',r=>number(r.visitors),r=>number(r.orders),r=>money(r.sales_cents)]);rows('#targetRows',d.targets||[],[r=>r.campaign||'—',r=>r.content||'—',r=>r.term||'—',r=>number(r.visitors)],'لم تُسجّل وسوم استهداف في الفترة المحددة.');$('#devices').replaceChildren(...(d.devices||[]).map(x=>node('span',({mobile:'هاتف',desktop:'كمبيوتر',tablet:'جهاز لوحي'}[x.device]||'غير معروف')+' · '+number(x.visitors))));chart(d.daily||[]);}
function chart(data){const c=$('#dailyChart');c.replaceChildren();if(!data.length){c.append(node('p','الرسم يظهر عندما تتوفر زيارات مسجّلة.'));return;}const max=Math.max(1,...data.map(x=>Number(x.visitors))),points=data.map((d,i)=>`${20+(i/Math.max(1,data.length-1))*720},${120-Number(d.visitors)/max*100}`).join(' ');const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 760 145');svg.setAttribute('role','img');svg.setAttribute('aria-label','المتصفحات المقاسة يومياً؛ التفاصيل في الجدول التالي');const line=document.createElementNS(ns,'polyline');line.setAttribute('points',points);line.setAttribute('fill','none');line.setAttribute('stroke','#cf1228');line.setAttribute('stroke-width','3');svg.append(line);data.forEach((d,i)=>{const dot=document.createElementNS(ns,'circle');dot.setAttribute('cx',String(20+i/Math.max(1,data.length-1)*720));dot.setAttribute('cy',String(120-Number(d.visitors)/max*100));dot.setAttribute('r','4');dot.setAttribute('fill','#cf1228');svg.append(dot);});c.append(svg);}
$('#orderStatus').onchange=()=>{offset=0;orders(true).catch(e=>notice(explain(e),true));};$('#moreOrders').onclick=()=>orders(false).catch(e=>notice(explain(e),true));
async function orders(reset){if(reset)offset=0;const d=await api('orders?'+query()+'&status='+$('#orderStatus').value+'&offset='+offset);if(reset)$('#orderList').replaceChildren();for(const o of d.orders){const e=node('article',undefined,'order-card'),head=node('div',undefined,'section-title');head.append(node('h3',o.reference),node('span',labels[o.status],'status '+o.status));e.append(head,node('p',shortDate(o.created_at)+' · '+o.branch_id+' · '+o.fulfilment),node('p',o.customer_name+' · '+o.customer_phone),node('p',o.delivery_address||''));for(const l of o.lines)e.append(node('p',l.name_ar+' × '+l.quantity+' — '+money(l.line_total_cents)));e.append(node('p','رسوم التوصيل: '+money(o.delivery_fee_cents)),node('p',money(o.total_cents),'total'),node('p','المصدر: '+o.source+' / '+o.medium+' · '+(o.campaign||'لا توجد حملة')));const actions=node('div',undefined,'order-actions'),next={new:['confirmed','cancelled'],confirmed:['completed','cancelled'],completed:['refunded']}[o.status]||[];next.forEach(s=>{const b=node('button',labels[s],s==='completed'?'primary':'');b.onclick=async()=>{const question=s==='completed'?'هل اكتمل الطلب فعلياً وتم تحصيل قيمته؟ سيُضاف إلى المبيعات.':s==='refunded'?'هل تم استرداد كامل قيمة الطلب فعلياً؟ سيتم طرحها من المبيعات.':'تغيير حالة الطلب إلى '+labels[s]+'؟';if(!confirm(question))return;b.disabled=true;try{await api('order-status',{id:o.id,status:s});await orders(true);}catch(err){notice(explain(err),true);}finally{b.disabled=false;}};actions.append(b);});e.append(actions);$('#orderList').append(e);}if(!d.orders.length&&reset)$('#orderList').append(node('div','لا توجد طلبات مسجّلة في الفترة والحالة المختارة.','empty'));offset=d.next_offset;$('#moreOrders').hidden=!d.has_more;}
async function menu(){allProducts=(await api('products')).products;renderProducts();}
function renderProducts(){const q=$('#productSearch').value.trim().toLowerCase();$('#productList').replaceChildren();for(const p of allProducts.filter(x=>(x.name_ar+' '+x.name_en+' '+x.id).toLowerCase().includes(q))){const card=node('article',undefined,'product-card'+(p.active?'':' inactive'));if(p.image_url){const img=node('img');img.src=p.image_url;img.alt=p.name_ar;img.loading='lazy';card.append(img);}const copy=node('div',undefined,'product-copy');copy.append(node('h3',p.name_ar),node('small',p.name_en),node('div',money(p.price_cents),'price'),node('small',p.active?(p.available?'منشور · متاح':'منشور · غير متاح'):'مخفي'));const b=node('button','تعديل');b.onclick=()=>editProduct(p);card.append(copy,b);$('#productList').append(card);}}
$('#productSearch').oninput=renderProducts;$('#newProduct').onclick=()=>editProduct(null);$('#closeProduct').onclick=()=>$('#productDialog').close();
function editProduct(p){edited=p;const f=$('#productForm');f.reset();$('#productError').textContent='';$('#uploadStatus').textContent='';$('#productHeading').textContent=p?'تعديل الصنف':'إضافة صنف';f.elements.id.readOnly=!!p;for(const name of ['id','name_ar','name_en','description_ar','description_en','category','image_url','tag','sort_order'])f.elements[name].value=p?.[name]??(name==='category'?'meals':name==='sort_order'?allProducts.length:'');f.elements.price.value=p?(p.price_cents/100).toFixed(2):'';for(const n of ['active','available','featured'])f.elements[n].checked=p?!!p[n]:n!=='featured';$('#productDialog').showModal();}
$('#productForm').elements.name_en.onblur=()=>{const f=$('#productForm');if(!edited&&!f.elements.id.value)f.elements.id.value=f.elements.name_en.value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70);};
$('#productImage').onchange=async()=>{const file=$('#productImage').files[0];if(!file)return;const b=$('#saveProduct');b.disabled=true;$('#uploadStatus').textContent='جارٍ تجهيز ورفع الصورة...';try{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>20000000)throw Error('INVALID_IMAGE_URL');const bitmap=await createImageBitmap(file),scale=Math.min(1,1400/Math.max(bitmap.width,bitmap.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(bitmap.width*scale));c.height=Math.max(1,Math.round(bitmap.height*scale));c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();const blob=await new Promise(r=>c.toBlob(r,'image/webp',.85));if(!blob||blob.size>2097152)throw Error('IMAGE_TOO_LARGE');const base64=await new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result).split(',')[1]);fr.onerror=reject;fr.readAsDataURL(blob);});const result=await api('upload',{mime:blob.type,base64});$('#productForm').elements.image_url.value=result.url;$('#uploadStatus').textContent='تم رفع الصورة. اضغطوا حفظ لتطبيقها على الصنف.';}catch(err){$('#uploadStatus').textContent=explain(err);}finally{b.disabled=false;}};
$('#productForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=$('#saveProduct');b.disabled=true;$('#productError').textContent='';try{const p={version:edited?.version||0,price_cents:Math.round(Number(f.elements.price.value)*100),sort_order:Number(f.elements.sort_order.value)};for(const n of ['id','name_ar','name_en','description_ar','description_en','category','image_url','tag'])p[n]=f.elements[n].value;for(const n of ['active','available','featured'])p[n]=f.elements[n].checked;await api('products',p);$('#productDialog').close();await menu();notice('تم حفظ الصنف. يظهر للزبائن عند تحديث المنيو.');}catch(err){$('#productError').textContent=explain(err);}finally{b.disabled=false;}};
async function audit(){const d=await api('audit');rows('#auditRows',d.entries,[r=>shortDate(r.created_at),r=>({product_saved:'حفظ صنف',order_status:'حالة طلب',password_changed:'تغيير كلمة المرور',image_uploaded:'رفع صورة'}[r.action]||r.action),r=>r.subject,r=>JSON.stringify(r.details)]);}
setInterval(()=>{if(!document.hidden&&!$('#workspace').hidden&&['dashboard','orders'].includes(currentTab))refresh();},60000);
api('me').then(d=>d.must_change_password?showPassword():signedIn()).catch(()=>signedOut());
