/* Protected customer profiles and measured funnel; never substitute demo values. */
(()=>{'use strict';let listOffset=0,selectedPhone='',pending=0;
const q=s=>document.querySelector(s),make=(tag,text)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;};
const metrics=make('section');metrics.className='card';metrics.id='customerFunnel';metrics.innerHTML='<h2>رحلة الزبون المقاسة</h2><div id="funnelMetrics" class="metrics"></div><p class="hint">متصفحات فريدة وافقت على القياس. مشاهدة الصنف تعني فتح تفاصيله، لا مجرد ظهور بطاقته. إضافة للسلة ≠ Checkout ≠ طلب مسجّل ≠ بيع مكتمل.</p><h3>الأصناف الأكثر مشاهدة</h3><div class="table-wrap"><table><thead><tr><th>الصنف</th><th>مشاهدات التفاصيل</th><th>مشاهدون فريدون</th><th>مرات الإضافة</th><th>متصفحات أضافت</th><th>وحدات أضيفت</th></tr></thead><tbody id="funnelProducts"></tbody></table></div>';q('#dashboard').prepend(metrics);
const tab=make('button','الزبائن');tab.dataset.tab='customers';q('.tabs').insertBefore(tab,q('[data-tab="audit"]'));
const panel=make('section');panel.id='customers';panel.className='tab-panel';panel.hidden=true;panel.innerHTML='<section class="card"><h2>Customers Analytics — سجل الزبائن</h2><p class="hint">الاسم والرقم كما أدخلهما الزبون؛ تجميع الرقم ليس إثباتاً للهوية. لا يظهر زائر مجهول كزبون معروف. المبيعات من الطلبات المكتملة ناقص الاستردادات.</p><form id="customerSearchForm" class="date-fields"><label>الاسم أو رقم الهاتف<input id="customerSearch" type="search" maxlength="100" autocomplete="off"></label><label>الترتيب<select id="customerSort"><option value="recent">آخر طلب</option><option value="orders">الأكثر طلباً</option><option value="spend">الأعلى إنفاقاً</option></select></label><button type="submit" class="primary">بحث</button></form><p id="customerListStatus"></p><div id="customerList"></div><button type="button" id="customerMore" hidden>المزيد</button></section><section id="customerProfile" class="card" hidden></section>';q('#workspace').append(panel);
async function crm(route,data){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const r=await fetch('/api/insights/admin/'+route,{method:'POST',credentials:'same-origin',cache:'no-store',signal:controller.signal,headers:{'Content-Type':'application/json','X-Afandi-Request':'1'},body:JSON.stringify(data||{})});const d=await r.json();if(!r.ok){if(r.status===401)signedOut();throw Error(d.error||'SERVICE_UNAVAILABLE');}return d;}finally{clearTimeout(timer);}}
const period=()=>({from:q('#fromDate').value,to:q('#toDate').value});function safeDate(d){return d?shortDate(d):'غير متوفّر';}function smallMetric(title,value){const e=make('article');e.className='metric';e.append(make('span',title),make('b',value));return e;}
async function funnel(){const ticket=++pending,range=period(),d=await crm('funnel',range);if(ticket!==pending||JSON.stringify(period())!==JSON.stringify(range)||q('#workspace').hidden)return;const known=d.coverage_start&&Date.parse(range.to+'T23:59:59+04:00')>=Date.parse(d.coverage_start);q('#funnelMetrics').replaceChildren(...[['شاهدوا تفاصيل صنف',d.view_item_visitors],['أضافوا للسلة',d.add_to_cart_visitors],['بدأوا Checkout',d.checkout_visitors]].map(([label,n])=>smallMetric(label,known?number(n):'غير متوفّر')));rows('#funnelProducts',d.top_products,[p=>p.name_ar||p.name_en,p=>number(p.views),p=>number(p.viewers),p=>number(p.add_actions),p=>number(p.add_visitors),p=>number(p.added_units)],known?'لا توجد تفاعلات مقاسة في الفترة.':'لم يبدأ تتبّع الأصناف والسلة بعد؛ لا توجد بيانات تاريخية.');}
async function customers(reset=true){if(reset){listOffset=0;q('#customerList').replaceChildren();selectedPhone='';q('#customerProfile').hidden=true;}const d=await crm('customers',{search:q('#customerSearch').value.trim(),sort:q('#customerSort').value,offset:listOffset});if(q('#workspace').hidden)return;q('#customerListStatus').textContent=d.coverage_start?'عدد ملفات أرقام الهواتف المسجّلة: '+number(d.total):'لم يبدأ سجل الطلبات الجديد بعد؛ البيانات القديمة غير متوفّرة.';for(const c of d.customers){const card=make('article');card.className='order-card';card.append(make('h3',c.name),make('p',c.phone),make('p',number(c.order_count)+' طلب مسجّل · '+money(c.net_sales_cents)+' صافي المبيعات'),make('p','آخر طلب: '+safeDate(c.last_order_at)));const b=make('button','عرض الملف والطلبات والأصناف المفضلة');b.type='button';b.onclick=()=>profile(c.phone).catch(e=>notice(explain(e),true));card.append(b);q('#customerList').append(card);}listOffset=d.next_offset;q('#customerMore').hidden=!d.has_more;}
async function profile(phone){selectedPhone=phone;const range=period(),d=await crm('customer',{phone,...range});if(selectedPhone!==phone||q('#workspace').hidden)return;const root=q('#customerProfile');root.hidden=false;root.replaceChildren(make('h2',d.name),make('p',d.phone),make('p','البيانات المجمّعة حسب رقم الهاتف المدخل؛ ملكيته غير متحقّقة.'));const m=make('div');m.className='metrics';m.append(smallMetric('كل الطلبات المسجّلة',number(d.lifetime.orders)),smallMetric('طلبات مكتملة',number(d.lifetime.completed_orders)),smallMetric('صافي الإنفاق الموثق',money(d.lifetime.net_sales_cents)),smallMetric('طلبات الفترة المختارة',number(d.period.orders)));root.append(m,make('p','أول طلب: '+safeDate(d.first_order_at)),make('p','آخر طلب: '+safeDate(d.last_order_at)),make('p','آخر زيارة بموافقة الربط: '+safeDate(d.last_consented_site_visit)),make('h3','الأصناف المتكررة — طلبات مكتملة غير مستردة'));
if(!d.favorites.length)root.append(make('p','لا توجد أصناف من طلبات مكتملة حتى الآن.'));for(const p of d.favorites)root.append(make('p',(p.name_ar||p.name_en)+' · '+number(p.orders_count)+' طلب · '+number(p.units)+' وحدة · '+money(p.line_total_cents)));
root.append(make('h3','طلبات الفترة: '+range.from+' — '+range.to));for(const o of d.orders){const card=make('article');card.className='order-card';card.append(make('h4',o.reference+' · '+labels[o.status]),make('p',safeDate(o.created_at)+' · '+money(o.total_cents)),make('p','المصدر: '+o.source+' / '+(o.campaign||'—')));for(const l of o.lines)card.append(make('p',l.name_ar+' × '+l.quantity+' — '+money(l.line_total_cents)));root.append(card);}if(d.orders_truncated)root.append(make('p','هذه أول 100 نتيجة. ضيّقوا فترة التاريخ لعرض الطلبات الأقدم.'));
root.append(make('h3','المتابعة'));if(d.marketing_opt_in){const a=make('a','فتح WhatsApp للمتابعة');a.href='https://wa.me/'+d.phone;a.target='_blank';a.rel='noopener noreferrer';a.onclick=e=>{if(!confirm('تحققوا من موافقة الزبون الحالية قبل التواصل التسويقي. فتح الرابط لا يرسل رسالة تلقائياً.'))e.preventDefault();};root.append(make('p','يوجد اختيار موافقة مسجّل من الزبون. تحققوا من صحته ومن عدم سحبه قبل التواصل.'),a);}else root.append(make('p','لا توجد موافقة تسويقية مسجّلة؛ لا ترسلوا عروض متابعة.'));root.scrollIntoView({behavior:'smooth',block:'start'});}
const oldRefresh=refresh;refresh=async function(){await oldRefresh();try{if(q('#workspace').hidden)return;if(currentTab==='dashboard')await funnel();if(currentTab==='customers'){if(selectedPhone)await profile(selectedPhone);else await customers(true);}}catch(e){if(currentTab==='dashboard')q('#funnelMetrics').replaceChildren(make('p','تعذّر تحميل القياس. غير متوفّر، وليس صفراً.'));notice(explain(e),true);}};
tab.onclick=()=>{currentTab='customers';document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('selected',b===tab));document.querySelectorAll('.tab-panel').forEach(p=>p.hidden=p.id!=='customers');q('#datePanel').hidden=false;selectedPhone='';refresh();};q('#customerSearchForm').onsubmit=e=>{e.preventDefault();customers(true).catch(e=>notice(explain(e),true));};q('#customerMore').onclick=()=>customers(false).catch(e=>notice(explain(e),true));
const oldSignedOut=signedOut;signedOut=function(){pending++;selectedPhone='';q('#customerList').replaceChildren();q('#customerProfile').replaceChildren();q('#customerProfile').hidden=true;q('#funnelMetrics').replaceChildren();q('#funnelProducts').replaceChildren();oldSignedOut();};
})();
