import fs from 'node:fs';
import vm from 'node:vm';
import path from 'node:path';
const dest=process.env.SEO_OUTPUT||'.',origin='https://alafandichicken.com';
const source=fs.readFileSync('app.js','utf8').split('const $=')[0],context={};
vm.runInNewContext(source+';globalThis.items=products',context,{timeout:2000});
const items=Array.from(context.items).filter(p=>p.active!==false);
if(!items.length||items.some(p=>!(/^[a-z0-9][a-z0-9-]{0,79}$/).test(p.id)||!Number.isFinite(p.price)||p.price<0))throw Error('Invalid authoritative menu');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json=v=>JSON.stringify(v).replace(/</g,'\\u003c');
const url=(p,l)=>origin+(l==='ar'?'/ar':'')+'/menu/'+(p?p.id+'/':'');
const img=p=>p.image?new URL(p.image.replace(/^\.\//,'/'),origin).href:null;
const price=p=>Number(p.price).toFixed(2);
function page(p,lang){const ar=lang==='ar',name=p?p[lang]:ar?'قائمة الطعام':'Menu',title=name+(ar?' | أفندي تشيكن دبي':' | Al Afandi Chicken Dubai');
const desc=p?(p[lang+'Desc']||name)+(ar?' — اطلب من أفندي تشيكن دبي.':' — Order from Al Afandi Chicken Dubai.'):(ar?'تصفّح قائمة أفندي تشيكن: الوجبات والمشروبات والإضافات مع الأسعار، واختر فرعك لإكمال الطلب.':'Explore the Al Afandi Chicken menu, meal details, drinks and sides with current listed prices. Choose your branch to complete your order.');
const canonical=url(p,lang),other=ar?'en':'ar',image=p?img(p):origin+'/assets/menu/affandi-logo.jpeg',structured=p?{'@context':'https://schema.org','@type':'MenuItem','@id':canonical+'#item',name:p[lang],description:p[lang+'Desc']||p[lang],url:canonical,...(image?{image}:{}),offers:{'@type':'Offer',price:price(p),priceCurrency:'AED',url:canonical,availability:'https://schema.org/'+(p.available===false?'OutOfStock':'InStock')}}:{'@context':'https://schema.org','@type':'Menu',name:ar?'قائمة أفندي تشيكن دبي':'Al Afandi Chicken Dubai menu',url:canonical,inLanguage:lang,hasMenuItem:items.map(x=>({'@type':'MenuItem',name:x[lang],url:url(x,lang),offers:{'@type':'Offer',price:price(x),priceCurrency:'AED'}}))};
const breadcrumb={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:ar?'الرئيسية':'Home',item:origin+'/'},{'@type':'ListItem',position:2,name:ar?'المنيو':'Menu',item:url(null,lang)},...(p?[{'@type':'ListItem',position:3,name:p[lang],item:canonical}]:[])]};
const cards=(p?items.filter(x=>x.id!==p.id&&x.cat===p.cat).slice(0,6):items).map(x=>`<a class="item" href="${url(x,lang)}"><span>${esc(x[lang])}</span><b>AED ${price(x)}</b></a>`).join('');
return `<!doctype html><html lang="${lang}" dir="${ar?'rtl':'ltr'}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(desc.slice(0,180))}"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="en" href="${url(p,'en')}"><link rel="alternate" hreflang="ar" href="${url(p,'ar')}"><link rel="alternate" hreflang="x-default" href="${url(p,'en')}"><meta property="og:type" content="website"><meta property="og:site_name" content="Al Afandi Chicken Dubai"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc.slice(0,180))}"><meta property="og:url" content="${canonical}">${image?`<meta property="og:image" content="${esc(image)}">`:''}<link rel="icon" href="/afandi-icon-v1.png"><link rel="stylesheet" href="/menu-pages.css"><script type="application/ld+json">${json(structured)}</script><script type="application/ld+json">${json(breadcrumb)}</script></head><body><header><a href="/"><img src="/assets/menu/affandi-logo.jpeg" alt="Al Afandi Chicken Dubai" width="90" height="90"></a><a href="${url(p,other)}">${ar?'English':'العربية'}</a></header><main><nav aria-label="Breadcrumb"><a href="/">${ar?'الرئيسية':'Home'}</a> / <a href="${url(null,lang)}">${ar?'المنيو':'Menu'}</a>${p?' / '+esc(name):''}</nav><article class="detail">${p&&image?`<img class="dish" src="${esc(image)}" alt="${esc(name)}" width="720" height="720" fetchpriority="high">`:''}<div><p class="eyebrow">AL AFANDI CHICKEN · DUBAI</p><h1>${esc(name)}</h1><p>${esc(p?p[lang+'Desc']||name:desc)}</p>${p?`<strong class="price">AED ${price(p)}</strong><p>${ar?'اختر الفرع وطريقة الاستلام؛ أي رسوم توصيل تظهر عند إكمال الطلب.':'Choose your branch and fulfilment method. Any delivery fee is shown at checkout.'}</p><a class="order" href="/?item=${p.id}&lang=${lang}#menu">${ar?'اختر خياراتك وأضف للطلب':'Choose options and add to order'}</a>`:''}</div></article><section><h2>${ar?(p?'أصناف أخرى من القسم':'الأصناف والأسعار'):(p?'More in this category':'Menu items and prices')}</h2><div class="items">${cards}</div></section></main><footer><a href="mailto:info@alafandichicken.com">info@alafandichicken.com</a> · <a href="/">${ar?'العودة لموقع الطلبات':'Return to ordering website'}</a></footer></body></html>`;
}
const out=(file,value)=>{const p=path.join(dest,file);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,value);};
const urls=[origin+'/'];for(const lang of ['en','ar']){const prefix=lang==='ar'?'ar/menu':'menu';out(prefix+'/index.html',page(null,lang));urls.push(url(null,lang));for(const p of items){out(prefix+'/'+p.id+'/index.html',page(p,lang));urls.push(url(p,lang));}}
out('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+urls.map(x=>'<url><loc>'+esc(x)+'</loc></url>').join('')+'</urlset>');
out('robots.txt','User-agent: *\nAllow: /\nDisallow: /admin\nDisallow: /api/\nDisallow: /backend/\nDisallow: /tests/\nDisallow: /scripts/\nSitemap: '+origin+'/sitemap.xml\n');
out('menu-pages.css','*{box-sizing:border-box}body{margin:0;font:17px/1.6 system-ui,sans-serif;background:#fffdf9;color:#211d19}a{color:inherit}header,main,footer{max-width:1100px;margin:auto;padding:24px}header{display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid #e8e0d5}header img{object-fit:contain}h1{font-size:clamp(30px,5vw,50px);line-height:1.15}h2{font-size:24px}.detail{display:grid;grid-template-columns:1fr 1fr;gap:40px;align-items:center;padding:32px 0}.dish{width:100%;height:auto;aspect-ratio:1;object-fit:contain;background:white;border-radius:24px}.eyebrow{font-size:12px;letter-spacing:1px;font-weight:700}.price{font-size:30px}.order{display:inline-block;margin:12px 0;background:#bc1027;color:white;padding:14px 24px;border-radius:10px;font-weight:700;text-decoration:none}.items{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.item{display:flex;justify-content:space-between;align-items:center;gap:14px;padding:18px;background:white;border:1px solid #e8e0d5;border-radius:12px;text-decoration:none}.item:hover{border-color:#bc1027}.item b{white-space:nowrap}footer{border-top:1px solid #e8e0d5;font-size:14px;margin-top:32px}@media(max-width:650px){header,main,footer{padding:18px}.detail{grid-template-columns:1fr;gap:12px}.dish{max-height:340px}.items{grid-template-columns:1fr}.order{width:100%;text-align:center}}');
console.log(JSON.stringify({items:items.length,pages:items.length*2+2,sitemap_urls:urls.length,source:'Current app.js catalogue; no invented ratings, nutrition or claims.'}));
